from enum import Enum


class SemanticType(str, Enum):
    IDENTIFIER = "IDENTIFIER"
    PERSON_NAME = "PERSON_NAME"
    EMAIL = "EMAIL"
    PHONE = "PHONE"
    ADDRESS = "ADDRESS"
    DATE = "DATE"
    DATETIME = "DATETIME"
    CURRENCY = "CURRENCY"
    QUANTITY = "QUANTITY"
    PERCENTAGE = "PERCENTAGE"
    CATEGORY = "CATEGORY"
    STATUS = "STATUS"
    URL = "URL"
    BOOLEAN = "BOOLEAN"
    TEXT = "TEXT"


class ExtractionPattern(str, Enum):
    FULL_EXTRACT = "FULL_EXTRACT"
    INCREMENTAL = "INCREMENTAL"
    CHANGE_DATA_CAPTURE = "CHANGE_DATA_CAPTURE"
    STREAMING = "STREAMING"
    WEBHOOK_PUSH = "WEBHOOK_PUSH"
    POLLING = "POLLING"
    FILE_UPLOAD = "FILE_UPLOAD"
    QUERY = "QUERY"


class NodeType(str, Enum):
    SOURCE = "SOURCE"
    FILTER = "FILTER"
    MAP = "MAP"
    CAST = "CAST"
    ENRICH = "ENRICH"
    FLATTEN = "FLATTEN"
    PIVOT = "PIVOT"
    DEDUPE = "DEDUPE"
    VALIDATE = "VALIDATE"
    SINK_OBJECT = "SINK_OBJECT"
    SINK_EVENT = "SINK_EVENT"
    AGENT_RUN = "AGENT_RUN"
    LLM_CLASSIFY = "LLM_CLASSIFY"
    ATTACHMENT_PARSE = "ATTACHMENT_PARSE"


class PipelineStatus(str, Enum):
    RUNNING = "RUNNING"
    IDLE = "IDLE"
    FAILED = "FAILED"
    PAUSED = "PAUSED"
    DRAFT = "DRAFT"
    COMPLETED = "COMPLETED"


class ConflictType(str, Enum):
    VOCABULARY = "VOCABULARY"
    TYPE = "TYPE"
    GRANULARITY = "GRANULARITY"
    SCALE = "SCALE"


class ConflictResolution(str, Enum):
    NAMESPACE_BOTH = "NAMESPACE_BOTH"
    NORMALIZE_CANONICAL = "NORMALIZE_CANONICAL"
    KEEP_EXISTING = "KEEP_EXISTING"
    REPLACE = "REPLACE"
    PENDING = "PENDING"


class PiiLevel(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class Role(str, Enum):
    ADMIN = "ADMIN"
    DATA_ENGINEER = "DATA_ENGINEER"
    ANALYST = "ANALYST"
    VIEWER = "VIEWER"
    SERVICE_ACCOUNT = "SERVICE_ACCOUNT"
    AUDITOR = "AUDITOR"


class Permission(str, Enum):
    READ_CONNECTORS = "READ_CONNECTORS"
    WRITE_CONNECTORS = "WRITE_CONNECTORS"
    READ_PIPELINES = "READ_PIPELINES"
    WRITE_PIPELINES = "WRITE_PIPELINES"
    READ_ONTOLOGY = "READ_ONTOLOGY"
    WRITE_ONTOLOGY = "WRITE_ONTOLOGY"
    READ_EVENTS = "READ_EVENTS"
    WRITE_EVENTS = "WRITE_EVENTS"
    READ_AUDIT = "READ_AUDIT"
    ADMIN_ALL = "ADMIN_ALL"
